### ISSUE TITLE
Zabbix script

### ISSUE THREAD

**Issue by buzzzo** [creativeprojects/resticprofile#11]
Please share the script used to feed status.json in zabbix

**Comment by creativeprojects** [comment]
There it is:
[zbx_export_templates.xml.zip](https://github.com/creativeprojects/resticprofile/files/5145215/zbx_export_templates.xml.zip)

There are two templates in it:
- one for a passive agent
- one for an active agent

I have hard-coded an alert if the last backup is more than 30 hours ago, because all my backup are running once a day overnight.
I guess I can extract it into a macro so you can set it up the way you want.
I'll see if I get some time to do it. Anyway that's the version I use for now 👍

**Comment by creativeprojects** [comment]
FYI: I've added the Zabbix template to a contrib section:
https://github.com/creativeprojects/resticprofile/tree/master/contrib/zabbix
