### ISSUE TITLE
Show restic progress output

### ISSUE THREAD

**Issue by legg33** [creativeprojects/resticprofile#136]
Hi,
maybe I'm just unable to find the corresponding config, but is it currently not possible to show the restic progress output, when running through resticprofile? Right now I have no idea how long a backup etc. might take. If it's not possible right now it would be pretty nice if support could get added.

Thanks!

**Comment by creativeprojects** [comment]
You should get the output of the restic command.

I can see two reasons why it's not happening:
- you set the `extended-status` flag to `true`
- you redirect the output log to a file (or syslog)

If you haven't done any of these things, I will need more information how to find out what the issue is 😄

**Comment by legg33** [comment]
Now that you mention it: I wrapped resticprofile inside another small program, so that I can achieve what I mentioned in #135, by calling resticprofile for each profile separately. Just for fun I decided to try out golang for this and I think the culprit is [here](https://github.com/creativeprojects/resticprofile/blob/a5c1147376f24764ce071663d66154944037f354/wrapper.go#L415), because my little program is not detected as a terminal.


So I guess this can get closed. Sorry for bothering you :sweat_smile:
