### ISSUE TITLE
Install.sh issue v0.15

### ISSUE THREAD

**Issue by kenblood** [creativeprojects/resticprofile#171]
The install documentation for linux includes a sample curl command that downloads install.sh, and then executes it.   Install.sh depends on a few undefined variables () that are not set by it, nor themselves documented, so I can't get it to run on my system (MXlinux).   Qed: resticprofile, good as it may be, can't be installed or run here, or, I suspect,  on any system where those variables are not globally pre-set.  Please change install.sh or document the required values of its variables.

**Comment by jkellerer** [comment]
Hi @kenblood, the requirements of `install.sh` (generated in goreleaser) are quite basic so that most posix compliant environments with an available resticprofile release should be able to run it. When it does fail, it should print what is missing.

Do you have such (or any other error) output and could you post it?

E.g. what happens if you run the script with maximum debug output:

```shell
./install.sh -b path/to/bin -d -x
```

**Comment by kenblood** [comment]
@jkiellerer,   thanks for your quick reply, problem solved!     When I  tried install.sh again this time, I somehow found a directory on my file system that contained the various resticprofile files v0.20.0.   When I ran install.sh again it, it worked, and resticprofile 0.20.0 is now installed and usable.   I don't know how the variables issue got solved, install.sh still depends on them, but it did work this time, and is good to go!
