### ISSUE TITLE
introduce a "base dir" option

### ISSUE THREAD

**Issue by JesseRacine** [creativeprojects/resticprofile#183]
Currently, resticprofile runs from the current directory that you are in when you run it. I was thinking that there could be a "base-dir" option that would set the directory that resticprofile runs from. If this option were implemented then you could run resticprofile from any directory and the backup would still work, since the backup (source option) could then be relative to the base-dir.

**Comment by jkellerer** [comment]
Makes sense. Could simplify the creation of reusable profiles, when relative paths can be used in source and the base is configured separately.

**Comment by kohanla** [comment]
@jkellerer Thanks for implementing this. Hope it will be merged soon :-). This option is important.

**Comment by kohanla** [comment]
@jkellerer I tested this pull request now. In case anybody else want to test it. Install git and go, then run
```
git clone https://github.com/creativeprojects/resticprofile.git
cd resticprofile
git fetch origin pull/192/head:base-dir
git merge base-dir
make build-all
ls -l resticprofile*
```

It works! Thanks for your code! But I have one wish.

It seems not possible to set the base-dir on "command level" as well. But I would prefer to set the base-dir just for the backup command, because in most cases it is only necessary there.

And then one question. If you do

```
cd /tmp
resticprofile testrestic.restore latest --target .
```

where should resticprofile restore to if base-dir is set to '/'

In my opinion it should be /tmp, but it is for some reason '/'

That's why I would prefer to have an option to set the base-dir on command level. This would allow me to run restore without a base-dir.

**Comment by jkellerer** [comment]
Thanks a lot for testing it. That is very good feedback.

In the current form `base-dir` not only sets the base for source-paths but for anything that depends on the current working dir. For consistency, I think this is correct behaviour, however I also see your use case.

Will update the PR to add a separate option to set a base just for backup sources.

**Comment by kohanla** [comment]
> Will update the PR to add a separate option to set a base just for backup sources.

Thanks! I will test when it is ready.

**Comment by kohanla** [comment]
@jkellerer 
 
> Will update the PR to add a separate option to set a base just for backup sources.

Thanks for your PR! Just to clarify, did you add an option to set a base just for backup sources?

**Comment by jkellerer** [comment]
Yes, there are 2 options, `source-base` and `base-dir`

**Comment by kohanla** [comment]
Thanks! Will test when 0.23 is available.
