### ISSUE TITLE
Is it possible, and if so how, to configure a Windows task from a resticprofile running in WSL/WSL2 ?

### ISSUE THREAD

**Issue by Gaibhne** [creativeprojects/resticprofile#196]
Would be helpful if that was documented somewhere; it's understandable if that isn't implemented, but it's technically possible, so it's not obvious that it doesn't work.

**Comment by jkellerer** [comment]
Hi @Gaibhne, if you run the Linux version of `resticprofile` on WSL, you cannot schedule a Windows task since the Linux version doesn't contain the related Windows code and likely wouldn't have access to the APIs anyway.

There are cases indicating that it is in general possible to register a Windows task that starts WSL and runs a command but I'm not aware that a Linux command could configure this from inside WSL.

While you can start both, "`resticprofile.exe`" (Windows) and "`resticprofile`" (Linux) inside a WSL console, the one operates in the Windows world (e.g. will expect Windows paths to files) and the other will operate in the Linux world (e.g. needs `/mnt/c` to access `C:`). Also you need the corresponding `restic.exe` or `restic` versions.

Only the Windows version can use Windows task for scheduling. 

The Linux version supports scheduling via "systemd" (if running) or "crond" (global.scheduler: "crond"), though I haven't tried if crond works correctly, "systemd" did not in my quick test on WSL.

**Comment by jkellerer** [comment]
I'd prefer to use `resticprofile.exe` and `restic.exe` to backup files on Windows, since when using WSL with the Linux versions you may be missing file attributes and you won't be able to use snapshots on NTFS. 

If you'd like to backup files from within WSL (e.g. not from `/mnt/c`), [crond](https://www.howtogeek.com/746532/how-to-launch-cron-automatically-in-wsl-on-windows-10-and-11/) should be usable when starting it as task in Windows and configure crond in profiles:

```yaml
global:
  scheduler: crond
```

**Comment by Gaibhne** [comment]
No, no, I definitely want to run backups on the Windows side of things, hence asking for the setting up of a Windows task to do it; but dealing with config files and CLI tools tends to naturally fall on the Linux half of my life, so I started setting up the resticprofile config in WSL, only to wonder if it could then be used to set up the Windows task to run it on the 'host'. In hindsight maybe a silly question to begin with.
