### ISSUE TITLE
resticprofile flagged as WS.Reputation.1

### ISSUE THREAD

**Issue by si458** [creativeprojects/resticprofile#248]
Norton is flagging the resticprofile.exe as a virus (WS.Reputation.1) so i have to exclude it to use it

but virustotal also detected it as a virus from 1 other provider
https://www.virustotal.com/gui/file/7089b3872a1b6e2f04c19e88a4f58e93e800bb6e8caa77473380baafc3a1017d?nocache=1

this can be avoided if you sign the exe with a code signing cerificate

**Comment by jkellerer** [comment]
Agree in general that release signing would be good, e.g. GPT based like in restic. 

Code signing for Windows is a different story as it requires a paid certificate to make any sense (as far as I know) and even when there are discount options for open source this is not easy for a project like this.

According to a google search "WS.Reputation.1" is flagged by Norton for files with no reputation (yet). Not sure if code signing would make a difference, but it surely would help with creating exceptions based on certs instead of paths.

Btw. it looks like `restic.exe` has the same problem (and isn't code-signed either):
https://www.virustotal.com/gui/file/323d72588756e04437e7295b2da96f6e8e72252316569fa5ab6dddc44677a376
Several go binaries seem to be detected as _Trojan.Malware.300983.susgen_. Looks like a common issue of this heuristic detection that it triggers on go binaries (in **1** scanner out of 71).

**Comment by creativeprojects** [comment]
I'm not too sure how it really works for Windows but it looks like it's actually a lot more expensive than an Apple developer certificate 😵‍💫
