### ISSUE TITLE
Allow to set resticprofile `--log` in config file

### ISSUE THREAD

**Issue by zxcat** [creativeprojects/resticprofile#261]
There is `schedule-log` to redirect logs for scheduled tasks, but for manual run users have to use `--log` flag. This makes backup command longer than it can be. Also in this case some options are placed in config file, but some (`--log`) should be added by hand to `resticprofile` call. Is there a reason for this?

In my case some automated backups are scheduled and `schedule-log` works perfect, but some other depend on an event (some job finished and it's time to backup) and I have to run `resticprofile` with `--log` flag to keep things unified. If logs path changes, this change must be updated in two different places, which isn't good.
It would be great to set logging the same way for both cases (or at least put both options inside one config).
Is it possible to add `log` option to config?

**Comment by creativeprojects** [comment]
Yes this is possible, but it needs a bit of work.

As it turns out, resticprofile is already logging stuff way before loading the profile. It could be debugging messages, displaying a banner, a warning or errors.

So we have two options here:
- We can log to the console before the profile configuration is loaded, then move to the specified target. I don't like this option too much.
- We need to keep the logs in a buffer and wait until we know what the user has decided in the profile before sending these messages. I think this is a neater solution, but needs a bit of work

Then I'm also tempted to send one message to the console telling the user that all the logs are over there. Otherwise nothing will be displayed when running manually on the command line.

**Comment by thiscantbeserious** [comment]
>Then I'm also tempted to send one message to the console telling the user that all the logs are over there. Otherwise nothing will be displayed when running manually on the command line.

You already have schedule-log for that, no?  

Why don't just add both a log and schedule-log property to the global section 

that does the exact same behaviour as in the profiles - just aggregated?

While you're at it ... same would be nice for the status file! 

I'd love to see all three being able to configure globally / aggregated instead of having to do it per profile

**Comment by jkellerer** [comment]
@creativeprojects , regarding early log output: 

Had the early log output issue already when fixing #251, wanted to implement a memory buffered logger but realised it must be fixed in `clog` as it starts with console log by default and may be used in init functions prior to the clog config in main. 

So `clog` should use a small mem buffer and switch to another logger when the buffer is filled or a specific logger is chosen. This is a breaking change for the `clog` api as log output may get delayed. But I guess that should be fine. Can take care of the change if you want.

**Comment by creativeprojects** [comment]
> So `clog` should use a small mem buffer and switch to another logger when the buffer is filled or a specific logger is chosen. This is a breaking change for the `clog` api as log output may get delayed. But I guess that should be fine. Can take care of the change if you want.

This is a good idea 👍🏻 I want to finish scheduling in `v2` before starting on something else, so we'll see who's going to be ready to tackle it first 😉 

Don't worry about the breaking change, I'm the only one using this library anyway 😆 (unless it's been used in a private repository...) Also we could bump it to `v1`

**Comment by jkellerer** [comment]
Pending PR for clog: https://github.com/creativeprojects/clog/pull/12
