### ISSUE TITLE
[macos]: get rid of "/Volumes/Some` in backed up paths

### ISSUE THREAD

**Issue by zxcat** [creativeprojects/resticprofile#262]
More generally, it's a long-lived "leading path prefix" issue in `restic`: https://github.com/restic/restic/issues/2092.
E.g., I want to backup these paths:
- `/Volumes/Some/dirToBackup`
- `/Volumes/ext_hdd/docs`

And they should be put volume-independent in backup:
- `/dirToBackup`
- `/docs`

The official answer is to `cd /Volumes/Some` and then `restic backup dirToBackup`: (https://github.com/restic/restic/issues/2092#issuecomment-486789004).

So I thought `base-dir`, `source-base` or even `run-before: 'cd /Volumes/Some'` / `env` can help, but they didn't.
* `base-dir` and `source-base` resolve paths to absolute, so backup contains absolute paths again.
* And `run-before` fails ~~earlier~~, because relative `source` cannot be resolved without `base-dir` or `source-base` or proper `CWD`.

So the only way I found to make this work is something like:
```sh
cd  /Volumes/Some
resticprofile -c path-to-profile-dir/profiles.yaml backup
```
which is ugly enough : (
Furthermore, it seems, the scheduler configuration becomes even more tricker (and `groups` won't work at all).
I feel I need one more wrapper around `resticprofile` : )

Maybe I miss something and it can be resolved simpler with current `resticprofile` features?

**Comment by zxcat** [comment]
just found that the reason `run-before` fails is different: it doesn't preserve env vars or path (cwd) before calling `restic`. also it seems each item (it it's an array) runs on its own shell.
it would be helpful to have a note in docs clarifying that `run-*` commands are isolated

**Comment by creativeprojects** [comment]
You see, this is exactly why we resolve the backup paths before sending them to restic. Otherwise it's very difficult to point to the right ones, depending on where you start the command, and if you specify `base-dir` and `source-base` or not.

> it would be helpful to have a note in docs clarifying that run-* commands are isolated

This is a good point actually.

There was also a discussion about running the commands inside a configured shell environment:
https://github.com/creativeprojects/resticprofile/issues/182

Now, to help with your issue, have you looked at Synthetic Firmlinks in macOS? this is just a fancy name for hardlinks between different devices. I haven't used it myself but it looks like it can solve your problem?

https://derflounder.wordpress.com/2020/01/18/creating-root-level-directories-and-symbolic-links-on-macos-catalina/

**Comment by zxcat** [comment]
Thanks for sharing Synthetic Firmlinks info!, didn't find it earlier, seems interesting.

But for now I just wrote a simple wrapper, which sets proper `cwd` before calling `resticprofile backup` and also passes some options like config and log paths. It's only used for `backup`, all other commands are processed well by `resticprofile` itself. Simple setting `cwd` has less impact on the system than creating something in the fs root.

**Comment by andreymal** [comment]
A wrapper for a wrapper?!

I would like to have an option to just change the working directory without resolving paths...
