### ISSUE TITLE
error setting process group: operation not permitted

### ISSUE THREAD

**Issue by cmonty14** [creativeprojects/resticprofile#296]
Hello,
running `resticprofile --dry-run backup` I get this error in CLI:
```
❯ resticprofile --dry-run backup
2023/12/10 11:26:28 using configuration file: /home/thomas/.config/resticprofile/profiles.conf
2023/12/10 11:26:28 error setting process group: operation not permitted
2023/12/10 11:26:28 profile 'default': starting 'backup'
2023/12/10 11:26:28 dry-run: /usr/bin/restic backup --exclude-caches --exclude-file=/home/thomas/.config/resticprofile/excludes --one-file-system --password-file=/home/thomas/.config/resticprofile/password.txt --repo=rclone:<nextcloud-server>:<path/to/my/repo> --tag=microos-home /home/thomas
2023/12/10 11:26:28 profile 'default': finished 'backup'
```

Can you please advise how to fix this error?

This is my current configuration file _/home/thomas/.config/resticprofile/profiles.conf_:
```
version = "1"

[global]
  # ionice is available on Linux only
  ionice = false
  ionice-class = 2
  ionice-level = 6
  # priority is using priority class on windows, and "nice" on unixes
  priority = "low"
  # run 'snapshots' when no command is specified when invoking resticprofile
  default-command = "snapshots"
  # resticprofile won't start a profile if there's less than 100MB of RAM available
  min-memory = 100

[default]
  repository = "rclone:<nextcloud-server>:<path/to/my/repo>"
  password-file = "password.txt"
  # initialize a repository if none exist at location
  initialize = false
  # add environment variables
  [default.env]
    TMPDIR= "/tmp"

  [default.backup]
    exclude-file = [ "excludes" ]
    exclude-caches = true
    one-file-system = true
    tag = "microos-home"
    source = "/home/thomas"
    verbose = false
```

THX

**Comment by jkellerer** [comment]
What fails under the hood is the call to `setpgid(0,0)`, which is meant to set the process group of `resticprofile` to the PID of itself so that `nice` values can be applied to all threads of the process using the GID (which is then same as the PID).

Checking for `operation not permitted` in relation to this POSIX call has several results but I haven't yet seen a clear reason why it fails, besides that processes that are the session leader (PID 1) are known to fail.

Maybe this helps to find more info. The main impact of this is that `priority = "low"` fails to apply when the error is logged.

**Comment by cmonty14** [comment]
I'm sorry, but I don't understand.
Just want to point out that my OS is MicroOS, an immutable OS, and relevant programs are running as local user (no root).

**Comment by creativeprojects** [comment]
This error means you cannot change the priority of the backup: `priority = "low"` in `global`. That's all it means. The backup is running perfectly fine with equal priority to all other applications running on your system.

I've seen this error before when resticprofile is running in a container; I suppose it's because the container is already running in a process group. Anyway I looked at MicroOS and it runs applications in containers so that's why you're seeing this error.

If you want to change the priority of the backup it would need to be done when creating the container. I don't know how you would do that with MicroOS though, I never used it before.

**Comment by jkellerer** [comment]
Had the same thought :). Containers and WSL don't seem to allow changing the process group.

**Comment by creativeprojects** [comment]
I was looking how we could detect it before applying the process group but it's not that obvious 🤔

**Comment by creativeprojects** [comment]
We should probably downgrade it to a warning actually, it's not affecting the result of the job in any way

**Comment by jkellerer** [comment]
Was about to write the same. Log level is warning already, maybe rephrasing the log message to let the user know that priority setting doesn't work would help.

**Comment by creativeprojects** [comment]
I've added some documentation about the most probable causes (container & WSL): https://0b4f96da.resticprofile.pages.dev/configuration/priority/

**Comment by cmonty14** [comment]
> Anyway I looked at MicroOS and it runs applications in containers so that's why you're seeing this error.

Actually this is not totally correct.
Binaries can run in containers or Linux OS (OpenSUSE).

**Comment by creativeprojects** [comment]
> Actually this is not totally correct. Binaries can run in containers or Linux OS (OpenSUSE).

What do you mean? you have a choice between running in a container of a full virtual machine?

**Comment by creativeprojects** [comment]
Sorry @cmonty14, it was a bug after all. I think I fixed the issue when running inside a container: https://github.com/creativeprojects/resticprofile/pull/339
