### ISSUE TITLE
generate.go: Mockery "breaks" RISC-V build

### ISSUE THREAD

**Issue by IngwiePhoenix** [creativeprojects/resticprofile#322]
Hello!

This is but a small issue that I faced while making a build for RISC-V to set up that box for backup.

```diff
diff --git a/generate.go b/generate.go
index 7398dc4..eb4050b 100644
--- a/generate.go
+++ b/generate.go
@@ -1,5 +1,5 @@
 package main

 //go:generate go install -v github.com/zyedidia/eget@latest
-//go:generate "${GOPATH}/bin/eget" vektra/mockery --upgrade-only --to "${GOPATH}/bin"
-//go:generate "${GOPATH}/bin/mockery" --config .mockery.yaml
+//go # generate "${GOPATH}/bin/eget" vektra/mockery --upgrade-only --to "${GOPATH}/bin"
+//go # generate "${GOPATH}/bin/mockery" --config .mockery.yaml
```

Mockery only has arm64 and x86_64 builds; so naturally this broke x)
```
2 candidates found (unsure architecture): please select manually
(1) mockery_2.42.0_Linux_arm64.tar.gz
(2) mockery_2.42.0_Linux_x86_64.tar.gz
Enter selection number: Error reading selection
generate.go:4: running "/root/go/bin/eget": exit status 1
make: *** [Makefile:89: prepare] Error 1
```

Thought it might be interesting for you to know! I am not very familiar with the Go build system - let alone what Mockery is for and stuff. So I didn't make this a PR or anything.

I am running on a VisionFive2 with a nearly upstream Debian 12 (only the kernel is held back by two un-merged changes thus far) but I still expect breakage once in a while... so, ResticProfile seemed like a good choice.

Thanks for the awesome tool and kind regards,
Ingwie

**Comment by creativeprojects** [comment]
Hey!

When I started the project I decided to generate the same list of pre-built binaries as restic.
I was just looking on the latest GitHub release and they've indeed added a lot more since (`riscv64` being one of them).

So we have a few options (in order of preference):
- we can add more targets to the release (we cross-build from linux amd64 so it's all good)
- we can build mockery ourselves in the `Makefile`
- we can add the files generated by mockery to the source

I think I'll probably go for the first one.

---

In the meantime, if you want to give it a try:

- clone the repository on an `amd64` or `arm64` machine. Linux, macOS, Windows, it doesn't matter.
- add this target to the `Makefile`:
```
build-riscv: prepare
	@echo "[*] $@"
	GOPATH="$(GOPATH)" \
	GOOS="linux" GOARCH="riscv64" $(GOBUILD) -o resticprofile -v -ldflags "-X 'main.commit=${BUILD_COMMIT}' -X 'main.date=${BUILD_DATE}' -X 'main.builtBy=make'"
```
- you can cross-compile with `make build-riscv` and copy the `resticprofile` binary to your new fancy board 👍🏻 

---

For information, the files generated by mockery are those:

```shell
$ ls **/mocks
config/mocks:
NamedPropertySet.go	ProfileInfo.go		PropertyInfo.go		SectionInfo.go

monitor/mocks:
OutputAnalysis.go

schedule/mocks:
Handler.go
```

**Comment by IngwiePhoenix** [comment]
In that case, the first approach seems to be the best one. I just edited the `generate.go` and then build; it's working mighty fine. :)

Thanks for the snippet, will give it a shot in WSL on my amd64 maschine later.
