### ISSUE TITLE
Remove older backup when repository havent free space for new backup

### ISSUE THREAD

**Issue by WMP** [creativeprojects/resticprofile#42]
Hello, is possible to create option to remove old backup, when new backup havent free space to finish?

**Comment by creativeprojects** [comment]
Sadly, I don't think that's something resticprofile would be able to do automatically:

- If there's not enough disk space to complete a snapshot, `restic` will simply fail. At that point, resticprofile cannot guess why it has failed.
- Assuming resticprofile can guess that the disk is full, which snapshot to delete, and which one to keep?
- Assuming we delete the oldest one, what should we do if we cannot complete the backup? we could potentially end up with an empty repository?

I think disk size and number of snapshots to keep should be calculated beforehand so that we don't run out of disk space. If it still happens, I believe we need a manual intervention and reconfiguration.
